### ISSUE TITLE
[Bountiful compat] Bounties don't show up in-game; errors in log about invalid pool items

### ISSUE THREAD

**Issue by Febilian** [wildcardgamez/BuddyCards#11]
This is my full [latest.log](https://gist.github.com/Febilian/7dacbfe2e58889710431501343e23201).

I recognize that's a LOT of text to sift through, so I singled out the part that seemed relevant below.

`Forge 36.1.4`
`Buddycards-1.16.5-2.2.2`
`Bountiful-1.16.4-3.3.1`

> [11Apr2021 13:07:12.659] [Render thread/WARN] [ejektaflex.bountiful.BountifulMod/]: Invalid pool item: BountyEntry (item-tag) [Item: buddycards:cards, Amount: 0 [[1..64]], Worth: 350, NBT: null, Weight: 1000]
> [11Apr2021 13:07:12.659] [Render thread/WARN] [ejektaflex.bountiful.BountifulMod/]: Invalid pool item: BountyEntry (item-tag) [Item: buddycards:set1_cards, Amount: 0 [[1..32]], Worth: 350, NBT: null, Weight: 1000]
> [11Apr2021 13:07:12.659] [Render thread/WARN] [ejektaflex.bountiful.BountifulMod/]: Invalid pool item: BountyEntry (item-tag) [Item: buddycards:set1s_cards, Amount: 0 [[1..12]], Worth: 400, NBT: null, Weight: 600]
> [11Apr2021 13:07:12.660] [Render thread/WARN] [ejektaflex.bountiful.BountifulMod/]: Invalid pool item: BountyEntry (item-tag) [Item: buddycards:set2_cards, Amount: 0 [[1..24]], Worth: 375, NBT: null, Weight: 150]
> [11Apr2021 13:07:12.660] [Render thread/WARN] [ejektaflex.bountiful.BountifulMod/]: Invalid pool item: BountyEntry (item-tag) [Item: buddycards:set3_cards, Amount: 0 [[1..16]], Worth: 400, NBT: null, Weight: 75]
> [11Apr2021 13:07:12.660] [Render thread/WARN] [ejektaflex.bountiful.BountifulMod/]: Invalid pool item: BountyEntry (item-tag) [Item: buddycards:epic_cards, Amount: 0 [[1..12]], Worth: 900, NBT: null, Weight: 200]
> [11Apr2021 13:07:12.660] [Render thread/WARN] [ejektaflex.bountiful.BountifulMod/]: Invalid pool item: BountyEntry (item-tag) [Item: buddycards:packs, Amount: 0 [[1..32]], Worth: 2500, NBT: null, Weight: 500]

**Comment by wildcardgamez** [comment]
I'll have to look into it, it mightve been a change to how integration is done on their side and I may have to update it accordingly. The game is still playable right? I'll get a fix out in the next patch.

**Comment by Febilian** [comment]
Yeah, it isn't causing any noticeable issues other than the cards not showing up as bounties as far as I can tell - I only noticed because I saw this in the logs.

**Comment by Febilian** [comment]
I think I found out what's going on - there were apparently issues with bounties related to item tags, so they've been disabled in recent releases of Bountiful. The Buddycards bounties aren't the only ones not working because of this.

https://github.com/ejektaflex/Bountiful/blob/develop/CHANGELOG.md#removals

**Comment by wildcardgamez** [comment]
So it's a problem with bountiful, they'll probably fix it soon.
