### ISSUE TITLE
New style foils/shinies don't work with Bountiful bounties

### ISSUE THREAD

**Issue by KotetsuRedwood** [wildcardgamez/BuddyCards#26]
New style foil cards don't work with bounties from Bountiful that require cards. 

Found this bug on a custom modpack.

BuddyCards version: 2.5.0
Bountiful version: 3.3.1
Forge version: 36.1.31

These mods started as earlier versions in modpack, if that helps diagnosis

**Comment by wildcardgamez** [comment]
Will fix it, forgot to fix the deprecated stuff for a few other things too when I think about it

**Comment by wildcardgamez** [comment]
https://github.com/wildcardgamez/BuddyCards/commit/52f9f38e8198f6f0100ad8b427f03f941c733396
should be fixed for next update, not 100% sure
