### ISSUE TITLE
Multi-language support in 1.16

### ISSUE THREAD

**Issue by Subilan** [wildcardgamez/BuddyCards#30]
Does BuddyCards for 1.16 support multi-language? I want to translate it on my own, but I didn't seem to find a language file in `config`. However, I did found the Chinese translation in this repository... Maybe I was wrong.

Another question: Is the multi-language support only available in 1.17? If I want to use it in 1.16, changing the text in source code and rebuilding it is the only solution, right?

**Comment by wildcardgamez** [comment]
you should be able to add the same lang file I guess

**Comment by Subilan** [comment]
What...?
Did you mean putting a lang file into its `config` directory?

I am currently using BuddyCards for 1.16.

**Comment by wildcardgamez** [comment]
No I mean using it like a language pack

**Comment by Subilan** [comment]
😅Sorry for my misunderstanding!

Could you please explain what is a language pack and how to use it?

**Comment by wildcardgamez** [comment]
I mean like a resource pack I think resource packs work the same way as
normal mod assets, so if you just made a Lang folder in the assets and put
in the 1.17 translations in it it'd work. Idk what to tell you but this
isn't an issue in the latest version so I'm going to close it
