### ISSUE TITLE
[Bug] Missing Medal for Byg set/Not able to complete armor and tools

### ISSUE THREAD

**Issue by Philipp766** [wildcardgamez/BuddyCards#33]
i wanted to see how strong the tools/armor are if you have 100% completion. Once i had all 27 cards of each type together, both normal and "shiny", I noticed that Byg doesn't have an Advancement and i didn't get a Medal. 
On top of that, the Completion is stuck at 96% but i have every card and advancement (assuming there are no invisible ones).

**Comment by wildcardgamez** [comment]
I'll look into the byg medal, but what version of buddycards are you using?
On top of that, not all cards register perfectly for pickups and sometimes
don't mark properly in the stats used for power. Is the advancement not
completing or is it just not there at all?

**Comment by Philipp766** [comment]
I am using the newest 1.16 version (2.5.2). If i saw it correctly, the Byg advancement wasnt there at all. Do i have to have all cards in my normal inventory or do binders or boxes suffice for the completion. as I said, i have all cards but didnt get the medal for it either.

**Comment by wildcardgamez** [comment]
Assuming that biomes you'll go is installed, it's probably an issue with
the advancement parameters. I'll take a look at it tomorrow.

**Comment by Philipp766** [comment]
Actually, Byg isnt installed as I'm playing Crate: Above and Beyond. If that is the cause, its ok by me that i can't complete the collection. I didnt know it was a problem.

**Comment by wildcardgamez** [comment]
Yep, you can't do anything for sets that aren't loaded, although you can get them via mystery packs, which are the way to get currently unavailable cards
