### ISSUE TITLE
Nether Medal BBII No Absorbtion II [Create Above & Beyond]

### ISSUE THREAD

**Issue by DevianProdigy** [wildcardgamez/BuddyCards#35]
Equipping the Nether Medal With BBII only applies fire res but no absorbtion II 

![image](https://user-images.githubusercontent.com/43588415/142321933-15a73488-5c72-4e53-aa18-7b4619b9a94a.png)
![image](https://user-images.githubusercontent.com/43588415/142322485-165e388b-6c04-4f8c-98a0-b1042cfe72d6.png)

**Comment by wildcardgamez** [comment]
This was never an issue? It's been ages since that was the effect. In the
guidebook it says it gives fire resistance, and with higher levels, buffs
when on fire such as strength and speed iirc

**Comment by wildcardgamez** [comment]
Not an issue, reporter has old info

**Comment by DevianProdigy** [comment]
Oh i was going with the info on the readme my bad need to craft the book, thanks for the quick response amazing mod
