### ISSUE TITLE
Buddycard rod+hook don't give cards when used in offhand

### ISSUE THREAD

**Issue by TaeoG** [wildcardgamez/BuddyCards#36]
A mod called "Fishing Real" allows you to pull up the fish entities instead of the fish items, but this typically means you fish with your offhand and hold a weapon in you main hand to whack them when they come out of the water. If you do this, the buddysteel fishing tackle will never give you a card.

**Comment by wildcardgamez** [comment]
I'll look into it in a bit

**Comment by TaeoG** [comment]
Also you can't get cards from mods like reliquary that have blocks that will fish for you. In that case I didn't expect that it would, but it would be nice

**Comment by wildcardgamez** [comment]
This should be an easy fix of just messing around with how I check if the rod is held, expect it fixed in the next 1.16 release

**Comment by wildcardgamez** [comment]
https://github.com/wildcardgamez/BuddyCards/commit/91cab7090753bcc4668a01623a84326c8a4cd7e8 fixed
