### ISSUE TITLE
Luminis pickaxe actually decreases odds for getting Deep Luminis instead of increasing them

### ISSUE THREAD

**Issue by bCalabrese** [wildcardgamez/BuddyCards#38]
https://github.com/wildcardgamez/BuddyCards/blob/c88133e99355f3bbba3a02e7656a9a2ae6863cfc/src/main/java/com/wildcard/buddycards/blocks/LuminisOreBlock.java#L31

The ternary is inverted and gives you 5% additional deepOdds if you are holding anything but a Luminis Pickaxe.

Since larger deepOdds effectively increases your chance at getting deep luminis, this seems like the opposite of what the intended behavior would be.
https://github.com/wildcardgamez/BuddyCards/blob/c88133e99355f3bbba3a02e7656a9a2ae6863cfc/src/main/java/com/wildcard/buddycards/blocks/LuminisOreBlock.java#L50-L51

**Comment by bCalabrese** [comment]
This also appears to be present in the 1.16.5 branch as well
https://github.com/wildcardgamez/BuddyCards/blob/fcca626be6f8cdf022ce91b2aa43be9ce59e4466/src/main/java/com/wildcard/buddycards/blocks/LuminisOreBlock.java#L39

**Comment by wildcardgamez** [comment]
Ah, I think I made this back when I was getting into more complicated stuff like ternary operators. I'll fix it for the 1.16 branch, but I'm planning on dropping 1.17 support, as 1.18 is about ready for release and I don't want to be working on 3 versions.

**Comment by wildcardgamez** [comment]
fixed https://github.com/wildcardgamez/BuddyCards/commits/1.16.5
