### ISSUE TITLE
Medallion Token Did Not Duplicate

### ISSUE THREAD

**Issue by FreeMarcher** [wildcardgamez/BuddyCards#39]
Using a **Medallion Token** on a **Farmer's Delight Set Buddy Medal** gave us a singular medal rather than duplicating the existing one. I had lost my medal on death, and so my wife used up a lot of resources attempting to create me a new one. Instead, she lost her own medal and her epic cards in the process. I did not want to cheat myself a new one, but ended up using /give to materialize it anyway so that she would have hers back, but it doesn't discount the resources and time she had to spend.

**Comment by wildcardgamez** [comment]
It's quite odd. I've heard a few reports of this issue and will be temporarily disabling these recipes for the next patch until I could figure something out

**Comment by wildcardgamez** [comment]
https://github.com/wildcardgamez/BuddyCards/commit/fdd16b05b3880a69383fc120bb739722512e93ad finished that
