### ISSUE TITLE
 JEI mode and Buddy card error 

### ISSUE THREAD

**Issue by Craft374** [wildcardgamez/BuddyCards#4]
Run JEI mode and Buddy card mode.
An error occurs when you enter the world.
[crash-2021-03-02_16.06.44-client.txt](https://github.com/wildcardgamez/BuddyCards/files/6066758/crash-2021-03-02_16.06.44-client.txt)

(There may be an error with the sentence using Google Translator)

**Comment by Craft374** [comment]
I didn't put in aquaculture mode. sorry

**Comment by wildcardgamez** [comment]
Looks like you were using 2.0.0, 2.0.1 was specifically made to remove the bug.
