### ISSUE TITLE
Crash on startup 1.18.1

### ISSUE THREAD

**Issue by Moobien** [wildcardgamez/BuddyCards#42]
Love the idea of the mod so giving it a go. but ever since the release of ColonyCards and now BuddyCardsExpansions I am getting a crash on startup. 

BuddyCards: 3.0.5
BuddyCardsExpansions: 1.0.1
Colony Cards: 1.0.0

Attaching crash log and latest log.
Crashlog:
[crash-2022-02-27_03.33.40-fml.txt](https://github.com/wildcardgamez/BuddyCards/files/8147021/crash-2022-02-27_03.33.40-fml.txt)
[latest.log](https://github.com/wildcardgamez/BuddyCards/files/8147023/latest.log)
![unknown (1)](https://user-images.githubusercontent.com/17806806/155851263-30a78807-0af8-4c1c-9e7e-807ab7cd70cc.png)

**Comment by wildcardgamez** [comment]
Wrong github

**Comment by wildcardgamez** [comment]
Let me know on the core or expansions github if it persists after todays updates
