### ISSUE TITLE
Recipe for Dark Oak Card Display is missing, and Acacia's recipe is listed twice.

### ISSUE THREAD

**Issue by jackk225** [wildcardgamez/BuddyCards#6]
The Dark Oak Card Display item shows up in JEI, but the recipe is missing and it can't be crafted. The Acacia Card Display's recipe is listed twice.

**Comment by wildcardgamez** [comment]
Will take a look at it

**Comment by wildcardgamez** [comment]
Ok it's fixed now, it'll be good in the next update I send out
